name: Actions workflows
on:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
  # push:
  pull_request:
    types: [closed, reopened, opened, assigned] 
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Check out
        uses: actions/checkout@v3.5.3
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: simple action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Masha
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
